title: Yiwen Luo # your name (or website title) here
logo: "/images/profile_pics/profile_2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Carleton College Statistics Major Class of 2021
  <br><br>
  Actively Looking for Entry-Level Positions in Data Analytics & Data Science
  <br><br>
  <a href="https://www.linkedin.com/in/yiwen-luo-a8b122177/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
